services:
  biomes:
    build: 
      context: .
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    ports:
      - "18003:3000"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - biomes-net

  redis:
    image: redis:7.0.8-alpine
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - biomes-net

volumes:
  node_modules:
  redis_data:

networks:
  biomes-net:
    driver: bridge
